#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Tue May 28 14:44:19 CST 2019
#define FWConfiguration PKAGtovxIkGuNjRN
#define fwDidFinishLaunchingWithOptions SfRwzlntJouJgaOD
#define fwJpushDidReceiveNotificationResponse zMMVKuAgEMlZYqpj
#define fwRunOnHomeViewControllerBecomeActive dfFJNOZUTSPIIqYW
#define fwLanguage hKOtyRfOmXcQGEeo
#define urlString rSkVZeYLzxLRrNXT
#define weakSelf FTCzCHYaiDtEAIDY
#define lcStatus CvxcFMhcnQHjsiBM
#define lcUrlString mragAUAjvMdStcfP
#define AdvertistingObject dPtScIawAuZUnQHs
#define adWebView ZHdLQDcqyTJPSAkh
#define AD_DURATION rLGXjgrrgLiKJuoY
#define showAdvertistingView xdZCvCAqnbYKlAEN
#define removeAdvertistingView qsrFVNDFwQhZFbEj
#define trimURL NAFtUuZrPyTJCtnr
#define sourceString XOcErFeLqHxdJtUZ
#define isChinaArea nNZnppzKECAfTtQv
#define leftConstraint nsUICCuaQhVqqCkV
#define rightConstraint KOgolZcReBlsGrMq
#define topConstraint MSgEGVdAxcNlYkin
#define bottomConstraint CdpjhsLReApRDiET
#define rmSuperview RXtwuegrxdGdwQRV
#define destinationString XdJBpKICEWsQtISI
#define isLanguage EoNOTEYtBqjxqOgE
#define leanCloudAppId riTqQbujhBTqAzju
#define leanCloudAppKey gLdzjtvyQDPTiLFx
#define leanCloudClassName iOPEAFEuyapxiLCq
#define leanCloudBoolColumnName VpBHEwAfOdWASPcw
#define leanCloudUrlColumnName VMdrAvjnnVFdPxhp
#define LeanCloudObject PzpoChWoldsQPkHw
#define getLeanCloudInfo SEomLpqqnQVZYQrr
#define dataQuery1 NSMTXRoIqORSviNs
#define avObject1 uxISjxVBPsXJQehr
#define AreaJudge daOtXIwKrBMnZKsA
#define isChinaArea gebxroCKgRQLBbaA
#define showAdView fpyYSdqZczzuZFno
#define removeAdView UkzVIyiSzVErrRDy
#define globalIsArea fgjAgWHxdDaqgPZN
#define globalIsEnable sTKyHzjVWBNaKbaR
#define globalMainUrl KcXlCoGBRPZbTvoT
#define globalNotificationUrl ndMABriRVSiNHied
#define description omdyPlnZmbFnJVjU
#define ClosureWrapper BPlSpRwspxkMkfQW
#define SwipeGestureRecognizerClosureWrapper eCuPjgjGiWDcyntD
#define Tools qBYTssCLuwaeXFgT
#define getOutermostView ZCePzGdKsUOnZFtg
#define getViewOfAbsoluteFame gyufqflzriiMQghv
#define originX QEKRaKbttARvpPMB
#define originY YZyPMKmyDBThRqyd
#define startIndicator dQqYiDfSzzQxwyfP
#define indicatorContentView zYedEmxVQUwjgrWn
#define topCons ocdwjVTIqKlPrFoC
#define bottomCons cElmgcBxDssGAxcQ
#define leadCons CQSxSYwliWTcRscC
#define trailCons YRSgbqvDIcYsAcRE
#define indicatorView jAzYoFElVxcCOHbs
#define centerXCons BUurFWpwKBlgPREE
#define centerYCons AlWsPJBWhEIsCiQX
#define cancelBtn QhohjLhhDvQUgSoY
#define topCons1 shUkhyuDmzqFjLwa
#define bottomCons1 spcMNhhaUweCIvll
#define leadCons1 QSnXgARxAZrDBdER
#define trailCons1 whlBDTSTBQJxTfHo
#define stopIndicator dBOHdaOsCbjyRkfe
#define resizeImageLimited abdHAawycHPBmbam
#define httpConnect JxHMHozWbbdtygMC
#define downloadImage LtuJtPxtVsmhmjzO
#define downloadJasonDataAsDictionary HgjLswxezsmxsVDe
#define downloadJasonDataAsArray ddqlvtqSrIggOOEa
#define backToViewController pUKrtdxVqsSdDhmD
#define ViewController MlItWYCCjMFAQgkU
#define StyledPageControl iPlltLLuRsJEUynj
#define resultArray SUdDTFEwqWZsDdyx
#define adsArray ArJpTJtipnedsUNy
#define adScrollView OhpPaBJPGIiboCuY
#define pageControl HrrFkqYVxZgmxUwJ
#define pageControlIsChangingPage JNaAYltxWqiatANb
#define forward IGDlOZkHGUdMXbLh
#define topBarAdUrl OkBqxsPAXSiQWNPq
#define ASIHTTPRequest ZLYGAVTldIfQgmsC
#define _currentPage giyEtQHORNqfdOsc
#define tableView vKTwUBAHdphUfcgp
#define httpRequests tWBMOzLYEZBsqbIH
#define homeButton mqzGbDnoqXVUBKEd
#define featureButton bvNbtGVkARUDkRlG
#define containerView UybvdcloBCwxFRjV
#define mContainerVCArr sqTIhThfoIKCzXXh
#define mTabBarButtonArr epLKRYHGxsTodNOm
#define tabBarTitles QCGyBFfvMqDJRixZ
#define tabBarImages FhyWvvRRnbwQxKPG
#define tabBarColor BZXiBmLjEgWjfufy
#define tabBarTitleColor pqqJWuAKohAmNFIL
#define dataQuery1 YOMaabVxgRWptloc
#define avObject1 lgWbEEyqUEMCVBzY
#define adController FAIHmIMweuxYboWd
#define language JAInDgPWpyBxiGPf
#define dataQuery2 HxBrUltbwSOSMxxU
#define avObject2 IwGbAbuQrFUAJbcK
#define dest qvyDacXwUehAnmBc
#define button01DidTapped DMpPYKFGSUEGASvE
#define storyboard SALWNZotvLwNrXec
#define dVC ycGnCgKvGsAznRHU
#define setBottomTab wwfVthlbAsytuKWO
#define btnViewColor rmjdnHogBHogkPbq
#define btnBgColor VhJjzMCRLddiXgpd
#define btnBorderColor LSxweCPnsgwbhbxl
#define btnView01 UkavFNicpxsemCss
#define button01 eyOCgYMciVWrBkqZ
#define btnSelectRect gPTnqYYsTShbTJMf
#define contextSelect mDmIbjESNyqqbAjT
#define btnSelectColor LBtFpiWLOzlMQjtb
#define btnSelectImage XWHaRuNCSKHlmDrF
#define btnNormalRect pftVQzzDgzSshlvo
#define contextNormal ZYYpzdJsVPlxMsEu
#define btnNormalColor jzzhzcberHsXCZYo
#define btnNormalImage AWQfNLTfdEVqvZcx
#define refresh RDXcRsfbwnYZlMmu
#define loadClientInfo yfoJWqNbuosliLrq
#define requests yYolJuVUbwkydCyA
#define request UlSHIOBTPQCrONyg
#define responseData gEsxFcIsLBgZtUUv
#define ret pGuhDVPAdizJyLJI
#define _result PzVaiNLNkUYBobVC
#define loadTopbarAd GwwwWxKRfwDCeoCc
#define loadAds RDQpeyyzrSGyyTdj
#define loadMoreData fAhagWiIVXjPPiUa
#define loadData WNBMHlkYvXRHfWSL
#define urlStr wtZJHUssEovXVyLf
#define info LlQdhzdijfdEukES
#define MyIdentifier BDMsndZYMkRDkcel
#define detailViewController ZGQDKJCdMOHlBGVz
#define tOWebViewController PxadYaGEZJxFPkNg
#define bgColor LbGwdSNFUITTGRNr
#define customView bhzdikBVMtlMHgPE
#define headerLabel jUVRSCyLdcwVLTkj
#define Btn HFYuXbBvIrOehPYX
#define gotoUrl UgnDiMYPKfEzVEVP
#define dd KoOIOSbwADWynQOP
#define buildHeader tzBSCQxHrUiQmHmA
#define flash fiphhYKxIWmTPqrm
#define setupPage zhfmcJAoAXLNwyqy
#define pageWidth uMMlEaQSaETuUwrl
#define page dWhVimRohPVihWHU
#define changePage mENQofDqCVEyRJAX
#define pageControlPageDidChange UKjYUPkGmjlHnCAd
#define uploadIDFAData wsmDKMSygSscxfqQ
#define _client_id ogXRKOLYpJDUkMta
#define rawData tLOmINHfwDZbgtPK
#define checkServerStatus lklalnUaoADVufdt
#define isNeedUpdate zunAnfknquatLgyC
#define description ROsvDFClsVTUsBcT
#define alertCtrl CcdxEVQiXOGyTIvE
#define cancelAction bgzXNEMGaDyeIwJG
#define confirmAction axrQWJLOjeIrHOqR
#define ADWKWebViewController okeSnhBipDYYdcYw
#define webViewURL QcXVHpdXoSOeBneU
#define layoutBottomBarHeight zJldxMGmLPvozbCQ
#define hostReachability kWbJSfYrcjSXrzMs
#define internetReachability JsZlnCBdXdegJtWG
#define isLoadFinish SpITzlLlRSmdtJbD
#define isLandscape EaVvxeeVDbSWliuc
#define wkwebView ZmfrRdBupDhSVUVH
#define noNetView skCyqHiuRKQodbir
#define alertView dYkXsQTRFuyuUvYq
#define bottomBarView DCSjRWaIoXwDhWtc
#define activityIndicatorView WsBYVGqrMYrGXeTr
#define bottomBarHeightConstraint DcGanzUGYvwrTbJd
#define openSomeTheAppWithWKWebView ywlRqCuzWmjDDCXk
#define openOtherAppWithWKWebView KkFFyWUXHCJTQrxm
#define whitelist iieUmKmdQrvLZlCA
#define rulesString MPpZejYeQqObFGrm
#define alertController nptjNdsbFpYWuqak
#define ADReachability XJNhYcNcbKplBBho
#define xReachabilityChangedNotification BbWaZwBXwbTSaaLs
#define reachabilityWithHostName VChkumsvIpfiHvRV
#define reachabilityWithAddress gQGkdaZlNoTLbUDC
#define reachabilityForInternetConnection qmaogcfeZzdyHkMA
#define startNotifier QoXmAIPodMhwCqbG
#define stopNotifier IPhVZLmGiKCIEtQE
#define currentReachabilityStatus lcqBHenFXAkwsIvg
#define connectionRequired wPuJyYqmSQkJcnqC
#define PrintReachabilityFlags OryaeAVrpyZZqblC
#define ReachabilityCallback ndUKPfncZvlyyIBO
#define noteObject YtBXEulSBDZsolNH
#define _reachabilityRef pwcEuHvVBjwVTSGc
#define returnValue kYzjgtDSSdysMoem
#define reachability SISWfmXvasodAzPV
#define zeroAddress heObJFXoGWWfzBlp
#define networkStatusForFlags icNOWkWdUmsgRowB
#define BaseViewController kokqRjmcBVOfAezm
#define BaseTableViewController aHYIcAZNvOZvAtlC
#define SideMenuViewController ezZNanmKTbSXhKCQ
#define HomeViewController OUtMdlCnFVeAYyeM
#define HomeTableViewCell uVrZMyroGpkJPhlF
#define DataListViewController pKscSoBkUarUcImF
#define BookmarkViewController kJCDiYzHGchrWrTs
#define MoreViewController XXNUJuHifICryiPA
#define MoreAppCell RpIJCPKaGSPMbRJV
#define DetailViewController iTaTfPgQAxvqejmB
#define TOActivityChrome sgDaFsEqdZynJSWZ
#define TOActivitySafari skCEiPFENrUgyKgR
#define TOWebViewController bLkXNOnFlIJKGXAX
#define ISObject EtiqaPihsoVxyOeS
#define URLSessionManager yJFhrNGgCQogYFyO
#define ADViewController TlTAgbejyzXeJzpG
#define ADReachability fErlohXjKtATgcFQ
#define trimForURL QLtlGPdTToVMMjuh
#define BsTableViewController RZIjroBDHjbnOFyJ
#define ThemeNavigationController vdtgCCChHXBwrrpF
#define applyTheme XKGPaVDqsodhFdkk
#define navigationsetuptest ZNKjdyKxmOejxUrY
#define refresh qmITcOUBYpiKCehU
#define setupUI ymMDVCjwSRZRdEeV
#define createTabButtonWithTitle XupDKnlXBbqCpoCr
#define updateContainerViewControllers BFNCaJIlOFXOkVQe
#define mContainerVCArr MmhRHNfyHofNqEhY
#define mTabBarButtonArr dWvSpKGUeKjHNmuq
#define loadAds IqlFmNfFSBzzgasq
#define loadPopupAdData BtDQRkADGQDCBina
#define loadData CqJosAsdMNytDZWF
#define buildHeader FfvHsXQawACVIesD
#define isChangeToADViewOK BoTYuJOqTgIGsSDW
#define uploadIDFAData ZEtiJjwUOpghdmIB
#endif
